name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - '*'  # This triggers the action for any branch with an open pull request

  push:
    branches:
      - '*'  # This triggers the action on every push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install python-dotenv

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests/

